services:
  redis:
    image: redis:7.2.5-alpine
    ports:
      - "6379:6379"
    networks:
      - image-compressor-network


networks:
  image-compressor-network:
    driver: bridge
    name: image-compressor-network

